# MSSQL – local development
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=MediaServer;encrypt=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:media}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:H@rd2F0rg3t01}
