name: Cleanup Failed Runs

on:
    workflow_dispatch:
    schedule:
        # ┌───────────── minute (0 - 59)
        # │ ┌───────────── hour (0 - 23)
        # │ │ ┌───────────── day of the month (1 - 31)
        # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
        # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
        # │ │ │ │ │
        # * * * * *
        - cron: "0 0 1 * *"

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Cleanup Old Failed Runs
              shell: bash
              run: |
                  gh run list --limit=2000 --json databaseId,conclusion --jq '.[] | select(.conclusion=="failure" or .conclusion=="cancelled") | .databaseId' | xargs -n1 gh run delete || true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
